name = "box-rental-now"
account_id = "f12c21930f2db3497ae6ffbe5f7638aa"
main = "dist/_worker.js/index.js"

compatibility_date = "2026-04-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"

[images]
binding = "IMAGES"

[observability]
enabled = false
